service: sde-questions-api

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**

custom:
  stage: ${opt:stage, self:provider.stage}
  lambda-schedule: cron(0/2 * * * ? *)
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  create:
    handler: api/question/create.main
    events:
      - http:
          path: question
          method: post

  get:
    handler: api/question/get.main
    events:
      - http:
          path: question/{id}
          method: get

  list:
    handler: api/question/list.main
    events:
      - http:
          path: question
          method: get
